
#include "data_arrays.h"

char *categories[] = {
    "Furniture",
    "Office Supplies",
    "Technology"};

char *subcategories[] = {
    "Bookcases",
    "Chairs",
    "Labels",
    "Tables",
    "Storage",
    "Furnishings",
    "Art",
    "Phones",
    "Binders",
    "Appliances",
    "Paper",
    "Accessories",
    "Envelopes",
    "Fasteners",
    "Supplies",
    "Machines",
    "Copiers"};

char *cities[] = {
    "Dearborn",
    "Harrisonburg",
    "Palatine",
    "Madison",
    "Wheeling",
    "Troy",
    "Cary",
    "Danbury",
    "Warwick",
    "Freeport",
    "Laguna Niguel",
    "Summerville",
    "Westminster",
    "Green Bay",
    "Fairfield",
    "Westfield",
    "Thornton",
    "Allentown",
    "Roswell",
    "La Quinta",
    "Saint Charles",
    "Hillsboro",
    "Henderson",
    "Wilson",
    "Linden",
    "Mesquite",
    "Cedar Hill",
    "Lakeville",
    "Roseville",
    "Oswego",
    "San Antonio",
    "Hagerstown",
    "Gastonia",
    "Plantation",
    "Hattiesburg",
    "Haltom City",
    "Montebello",
    "Jackson",
    "Oceanside",
    "Eau Claire",
    "Rio Rancho",
    "Texarkana",
    "Lake Elsinore",
    "Buffalo Grove",
    "Washington",
    "Lindenhurst",
    "Auburn",
    "Pleasant Grove",
    "Miami",
    "Redding",
    "West Allis",
    "Lawton",
    "Coachella",
    "Englewood",
    "Waterbury",
    "Salem",
    "Fort Collins",
    "Rogers",
    "Hendersonville",
    "El Cajon",
    "Morgan Hill",
    "Waynesboro",
    "Inglewood",
    "San Angelo",
    "Macon",
    "Knoxville",
    "Hollywood",
    "Wichita",
    "Atlantic City",
    "Des Plaines",
    "El Paso",
    "Westland",
    "Reading",
    "Chula Vista",
    "Richardson",
    "Charlotte",
    "Alexandria",
    "Irving",
    "Cleveland",
    "Owensboro",
    "Dublin",
    "Mount Vernon",
    "Mansfield",
    "Conway",
    "Dover",
    "Carol Stream",
    "East Orange",
    "Whittier",
    "La Mesa",
    "Murray",
    "Chester",
    "Thomasville",
    "Kenner",
    "Homestead",
    "Morristown",
    "Huntington Beach",
    "Raleigh",
    "Lakeland",
    "Houston",
    "Omaha",
    "Santa Ana",
    "Bloomington",
    "Florence",
    "Southaven",
    "Harlingen",
    "Baytown",
    "Portage",
    "Buffalo",
    "Mobile",
    "Garden City",
    "Plainfield",
    "Columbia",
    "Aurora",
    "Skokie",
    "Waukesha",
    "Lake Charles",
    "Greensboro",
    "Spokane",
    "Pine Bluff",
    "Farmington",
    "Arlington",
    "Naperville",
    "Hempstead",
    "Chapel Hill",
    "Lansing",
    "Lebanon",
    "Palm Coast",
    "Port Arthur",
    "Las Vegas",
    "North Charleston",
    "Coral Gables",
    "Conroe",
    "Philadelphia",
    "Plano",
    "Yonkers",
    "Mesa",
    "Manteca",
    "Boynton Beach",
    "Frisco",
    "Atlanta",
    "Missouri City",
    "San Jose",
    "Corpus Christi",
    "Superior",
    "Sparks",
    "Ormond Beach",
    "Danville",
    "Tuscaloosa",
    "Kirkwood",
    "Austin",
    "Rochester",
    "Utica",
    "Bedford",
    "Shelton",
    "Orem",
    "Avondale",
    "Laredo",
    "Detroit",
    "Olympia",
    "Chesapeake",
    "Champaign",
    "Trenton",
    "Baltimore",
    "Garland",
    "Broomfield",
    "Bryan",
    "Bellingham",
    "Redmond",
    "Portland",
    "Oakland",
    "Manhattan",
    "Lowell",
    "Bayonne",
    "The Colony",
    "Scottsdale",
    "Overland Park",
    "Woodland",
    "Sanford",
    "Parma",
    "Pompano Beach",
    "Round Rock",
    "Monroe",
    "Long Beach",
    "Las Cruces",
    "Bakersfield",
    "Altoona",
    "Los Angeles",
    "Boise",
    "Coon Rapids",
    "Deltona",
    "Port Saint Lucie",
    "Franklin",
    "Manchester",
    "Temecula",
    "Longview",
    "New Brunswick",
    "Independence",
    "Fremont",
    "Tulsa",
    "Renton",
    "San Bernardino",
    "Norman",
    "League City",
    "Charlottesville",
    "Pomona",
    "Stockton",
    "Evanston",
    "Carrollton",
    "Chicago",
    "Maple Grove",
    "Deer Park",
    "Caldwell",
    "San Marcos",
    "Niagara Falls",
    "Draper",
    "Arlington Heights",
    "Fort Lauderdale",
    "Beverly",
    "San Clemente",
    "Saint Paul",
    "Lewiston",
    "Dallas",
    "Escondido",
    "Grand Prairie",
    "Longmont",
    "Lakewood",
    "Norwich",
    "Indianapolis",
    "Hoover",
    "La Porte",
    "Muskogee",
    "Lafayette",
    "Saint Louis",
    "Thousand Oaks",
    "Revere",
    "Virginia Beach",
    "San Gabriel",
    "San Luis Obispo",
    "Romeoville",
    "Odessa",
    "Covington",
    "Bellevue",
    "Salt Lake City",
    "Denver",
    "Murfreesboro",
    "Iowa City",
    "Coppell",
    "Mission Viejo",
    "Memphis",
    "Great Falls",
    "Dubuque",
    "Waco",
    "Missoula",
    "Leominster",
    "Rochester Hills",
    "Hickory",
    "Clarksville",
    "Santa Clara",
    "Elkhart",
    "Bolingbrook",
    "Modesto",
    "Richmond",
    "Anaheim",
    "Woodbury",
    "Yuma",
    "Edinburg",
    "Rockville",
    "Tempe",
    "Everett",
    "Gilbert",
    "Phoenix",
    "Beaumont",
    "Orlando",
    "Fayetteville",
    "Newark",
    "Providence",
    "Santa Fe",
    "Seattle",
    "Bristol",
    "Miramar",
    "Boca Raton",
    "Reno",
    "Quincy",
    "Waterloo",
    "Rock Hill",
    "Marion",
    "Concord",
    "Eagan",
    "Santa Barbara",
    "Elmhurst",
    "Oak Park",
    "Taylor",
    "Yucaipa",
    "Midland",
    "Mishawaka",
    "South Bend",
    "Hialeah",
    "Normal",
    "Clovis",
    "Tampa",
    "North Miami",
    "Rome",
    "Holland",
    "Park Ridge",
    "Fargo",
    "Newport News",
    "Glendale",
    "North Las Vegas",
    "Clifton",
    "Bossier City",
    "Oxnard",
    "Visalia",
    "Royal Oak",
    "Santa Maria",
    "Lake Forest",
    "Lorain",
    "Passaic",
    "Oklahoma City",
    "Hamilton",
    "College Station",
    "Mason",
    "Sacramento",
    "Bangor",
    "Jupiter",
    "Hackensack",
    "Tigard",
    "Edmonds",
    "Cuyahoga Falls",
    "Arvada",
    "Cincinnati",
    "Bullhead City",
    "Pembroke Pines",
    "Loveland",
    "Little Rock",
    "Woonsocket",
    "Kissimmee",
    "Pocatello",
    "Moreno Valley",
    "Decatur",
    "Saint Peters",
    "Coral Springs",
    "Minneapolis",
    "Abilene",
    "Pharr",
    "New Bedford",
    "Nashville",
    "Lodi",
    "Medford",
    "Salinas",
    "Greeley",
    "Cheyenne",
    "Albuquerque",
    "Tyler",
    "Apopka",
    "Logan",
    "Daytona Beach",
    "Antioch",
    "Lubbock",
    "Durham",
    "Brownsville",
    "Hot Springs",
    "Rancho Cucamonga",
    "Marietta",
    "Norfolk",
    "Nashua",
    "Appleton",
    "Milford",
    "Woodstock",
    "Redondo Beach",
    "Marysville",
    "Paterson",
    "Commerce City",
    "Milwaukee",
    "Pico Rivera",
    "Laurel",
    "Carlsbad",
    "Eugene",
    "Fort Worth",
    "Columbus",
    "Bartlett",
    "Pasadena",
    "Belleville",
    "Orange",
    "Grapevine",
    "Camarillo",
    "Murrieta",
    "Broken Arrow",
    "Vancouver",
    "Lawrence",
    "Redwood City",
    "Malden",
    "Perth Amboy",
    "New Albany",
    "Orland Park",
    "Pensacola",
    "Pearland",
    "Warner Robins",
    "Wilmington",
    "Lincoln Park",
    "Port Orange",
    "New York City",
    "Grove City",
    "Saint Petersburg",
    "Greenville",
    "Parker",
    "Bowling Green",
    "Provo",
    "Wausau",
    "Brentwood",
    "Meridian",
    "Akron",
    "Jamestown",
    "Tallahassee",
    "Gresham",
    "Peoria",
    "New Rochelle",
    "Sunnyvale",
    "New Castle",
    "Littleton",
    "Vacaville",
    "Bozeman",
    "Tamarac",
    "Asheville",
    "Edmond",
    "Sterling Heights",
    "Riverside",
    "Springfield",
    "Chattanooga",
    "Chandler",
    "Bridgeton",
    "Citrus Heights",
    "Layton",
    "Dearborn Heights",
    "Costa Mesa",
    "Watertown",
    "Suffolk",
    "Helena",
    "Des Moines",
    "Davis",
    "Sheboygan",
    "Cottage Grove",
    "San Mateo",
    "Marlborough",
    "Bethlehem",
    "Margate",
    "Clinton",
    "Burlington",
    "Allen",
    "Mentor",
    "Greenwood",
    "Cedar Rapids",
    "San Francisco",
    "Encinitas",
    "Gladstone",
    "Montgomery",
    "Redlands",
    "Tucson",
    "Olathe",
    "Keller",
    "La Crosse",
    "Chico",
    "Frankfort",
    "Glenview",
    "Athens",
    "Andover",
    "East Point",
    "Lancaster",
    "Jefferson City",
    "Toledo",
    "Saint Cloud",
    "Hesperia",
    "Lehi",
    "Gaithersburg",
    "Sierra Vista",
    "Springdale",
    "Amarillo",
    "Johnson City",
    "Melbourne",
    "Elyria",
    "Holyoke",
    "Gulfport",
    "Grand Island",
    "Hampton",
    "Fresno",
    "Highland Park",
    "Cambridge",
    "Georgetown",
    "Ontario",
    "Moorhead",
    "Vallejo",
    "Noblesville",
    "Saginaw",
    "Torrance",
    "Apple Valley",
    "Mount Pleasant",
    "West Palm Beach",
    "Jacksonville",
    "West Jordan",
    "Tinley Park",
    "Twin Falls",
    "Cranston",
    "Rapid City",
    "Kenosha",
    "Ann Arbor",
    "Louisville",
    "Urbandale",
    "Sandy Springs",
    "Canton",
    "Rockford",
    "York",
    "Burbank",
    "Vineland",
    "Aberdeen",
    "Delray Beach",
    "Kent",
    "Jonesboro",
    "Grand Rapids",
    "Texas City",
    "Middletown",
    "Billings",
    "Pasco",
    "Mcallen",
    "Meriden",
    "Pueblo",
    "Smyrna",
    "San Diego",
    "Huntsville",
    "Colorado Springs",
    "Goldsboro",
    "Medina",
    "Sioux Falls",
};

char *regions[] = {
    "West",
    "South",
    "North",
    "East",
    "Central"};

char *states[] = {
    "Utah",
    "North Carolina",
    "Iowa",
    "California",
    "Montana",
    "New York",
    "Texas",
    "Missouri",
    "Arkansas",
    "South Carolina",
    "New Jersey",
    "Vermont",
    "New Hampshire",
    "Connecticut",
    "Idaho",
    "Maine",
    "Virginia",
    "Oregon",
    "Washington",
    "Delaware",
    "Nebraska",
    "Kentucky",
    "Wisconsin",
    "Nevada",
    "Florida",
    "District of Columbia",
    "Maryland",
    "Massachusetts",
    "Indiana",
    "Kansas",
    "Minnesota",
    "Wyoming",
    "Alabama",
    "Georgia",
    "Louisiana",
    "West Virginia",
    "New Mexico",
    "Illinois",
    "Pennsylvania",
    "Michigan",
    "Oklahoma",
    "Rhode Island",
    "Arizona",
    "Colorado",
    "South Dakota",
    "Ohio",
    "Mississippi",
    "Tennessee",
    "North Dakota"};
